#!/bin/bash

AMI_ID="ami-09c813fb71547fc4f"
SG_ID="sg-06776cce51381651f" # replace with your SG ID
INSTANCES=("mongodb" "redis" "mysql" "rabbitmq" "catalogue" "user" "cart" "shipping" "payment" "dispatch" "frontend")
ZONE_ID="Z0193002ZK4VQFXB1ARL" # replace with your ZONE ID
DOMAIN_NAME="prasad84s.site" # replace with your domain

for instance in ${INSTANCES[@]}
do 


done

